{
 "title": "Routes",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "assetid",
    "label": "Asset ID",
    "query": "select distinct(assetid) from mobileassets.haulasset"
   }
  ]
 },
 "panels": [
  {
   "title": "Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select ts,  load as LOAD from mobileassets.haulasset where ts > $from and ts < $to and  assetid = '$assetid'"
    }
   ]
  },
  {
   "title": "RPM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select ts, rpm as RPM from mobileassets.haulasset where ts > $from and ts < $to and  assetid = '$assetid'"
    }
   ]
  },
  {
   "title": "Gear",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select ts, gear as GEAR from mobileassets.haulasset where ts > $from and ts < $to and  assetid = '$assetid'"
    }
   ]
  },
  {
   "title": "Fuel Remaining",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select ts, fuelremaining from mobileassets.haulasset where ts > $from and ts < $to and assetid = $assetid"
    }
   ]
  },
  {
   "title": "Location",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select ts,latitude, longitude from mobileassets.haulasset where ts > $from and ts < $to and  assetid = '$assetid'"
    }
   ]
  },
  {
   "title": "Air Filter Differential Pressure",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select ts, airfilterdiffpress from mobileassets.haulasset where ts > $from and ts < $to and assetid = $assetid"
    }
   ]
  },
  {
   "title": "Air Inlet Pressure",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select ts, airinletpress from mobileassets.haulasset where ts > $from and ts < $to and assetid = $assetid"
    }
   ]
  },
  {
   "title": "Crank Case Pressure",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select ts, crankcasepress from mobileassets.haulasset where ts > $from and ts < $to and assetid = $assetid"
    }
   ]
  },
  {
   "title": "Cabin Conditions",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select cabinsoundlevel, cabintemp from mobileassets.haulasset where ts > $from and ts < $to and assetid = $assetid"
    }
   ]
  }
 ]
}